name: Build sdm845-Kernelsu
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - version: 4.9.336
            arch: "arm64"
            out_file: "arch/arm64/boot/Image"
            kernel_make_cmd: "ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu Image"
            make_config: "sdm845_defconfig"

    name: Build sdm845_Kernelsu_kernel-${{ matrix.version }}
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    
    - name: install dependencies
      run: |
        sudo apt install gcc-aarch64-linux-gnu
        sudo apt install gcc-arm-linux-gnueabi
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -   
        echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main" | sudo tee -a /etc/apt/sources.list  
        sudo apt-get update -y 
        sudo apt install clang-12 llvm-12 -y
        sudo apt install binutils make python libssl-dev build-essential bc  bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git

    - name: Download kernel source and kernel su 
      run: |
        sudo -i
        cd $GITHUB_WORKSPACE
        git clone https://github.com/LineageOS/android_kernel_xiaomi_sdm845
        cd android_kernel_xiaomi_sdm845
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
        echo "CONFIG_KPROBES=y" >>arch/arm64/configs/sdm845_defconfig
        echo "CONFIG_KPROBES_ON_FTRACES=y" >>arch/arm64/configs/sdm845_defconfig
        echo "CONFIG_KVM=y"  >>arch/arm64/configs/sdm845_defconfig
        echo "CONFIG_VIRTUALIZATION=y" >>arch/arm64/configs/sdm845_defconfig

    - name: Build Kernel
      working-directory: android_kernel_xiaomi_sdm845
      run: |
       sudo -i
       export ARCH=arm64
       export SUBARCH=arm64
       make O=out CC=clang-12 sdm845_defconfig ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-
       make O=out CC=clang-12 -j8 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-
    - name: check
      run: |
       cd /home/runner/work/github-action-build-kernel/github-action-build-kernel/android_kernel_xiaomi_sdm845/out/arch/arm64/boot/
       ls
    - name: Upload boot directory
      uses: actions/upload-artifact@v3
      with:
        name: boot
        path: /home/runner/work/github-action-build-kernel/github-action-build-kernel/android_kernel_xiaomi_sdm845/out/arch/arm64/boot
      
